"""Updated ForeignKey to be nullable

Revision ID: b13e3020c945
Revises: d61f2a1f1772
Create Date: 2025-02-07 19:29:54.452904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13e3020c945'
down_revision = 'd61f2a1f1772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('strands', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('usertypes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertypes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('strand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('strands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
